# netlify.toml

[build]
  base = "frontend/client"         # مجلد الكود
  publish = "frontend/client/build" # مجلد النشر بعد build
  command = "npm run build"        # أمر بناء React

[build.environment]
  NODE_VERSION = "18"              # نسخة Node لضمان التوافق
  REACT_APP_API_URL = "https://event-management-system-j3ti-lehdjfmlc-rawan-2112s-projects.vercel.app"  # رابط الباك اند

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
